markdown: kramdown
highlighter: pygments
baseurl: "/webapi-eca"
title: "WebAPI ECA Engine Tutorial"
description: > # ignore new lines until next property
  Tutorials for the webapi-eca engine
max_priority: 10