markdown: kramdown
highlighter: pygments
baseurl: /webapi-eca
title: Reactivity on the Web
description: > # ignore new lines until next property
  Introduction &amp; Tutorials to Reactivity on the Web
max_priority: 10
github_username: dominicbosch