// Generated by CoffeeScript 1.4.0
(function() {
  var getElement, getElementAttribute, oldPicture;

  oldPicture = '';

  exports.checkForChange = function(url, tag) {
    return request(url, function(error, response, html) {
      var domTree, newPicture;
      if (!error && response.statusCode === 200) {
        domTree = cheerio.load(html);
        newPicture = domTree(tag).attr('src');
        if (oldPicture !== newPicture) {
          pushEvent({
            src: newPicture
          });
        }
        return oldPicture = newPicture;
      }
    });
  };

  getElement = function(url, startSelector, parentSelector, childSelector, cb) {
    return request(url, function(error, response, html) {
      var domTree;
      if (!error && response.statusCode === 200) {
        domTree = cheerio.load(html);
        log('got answer');
        return cb(domTree(startSelector).closest(parentSelector).children(childSelector));
      }
    });
  };

  getElementAttribute = function(url, startSelector, parentSelector, childSelector, attribute, cb) {
    return getElement(url, startSelector, parentSelector, childSelector, function(el) {
      return cb(el.attr(attribute));
    });
  };

  exports.getAttributeValue = function(url, startSelector, parentSelector, childSelector, attribute) {
    return getElementAttribute(url, startSelector, parentSelector, childSelector, attribute, function(val) {
      return pushEvent({
        attrName: attribute,
        attrVal: val
      });
    });
  };

  exports.getTagContent = function(url, startSelector, parentSelector, childSelector) {
    return getElement(url, startSelector, parentSelector, childSelector, function(el) {
      log('weee');
      log(el.first().text());
      return pushEvent({
        text: el.first().text()
      });
    });
  };

}).call(this);
